/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;

import hnhoteles.com.Additional;
import hotel.Price;
import javax.swing.JOptionPane;
import user.Administrator;

/**
 *
 * @author Stward
 */
public class AdministratorView extends javax.swing.JFrame {
    
    private Administrator administrator;
    
    public AdministratorView() {
        initComponents();
    }

    AdministratorView(Administrator administrator) {
        this.administrator = administrator;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        seasonCodeText = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        seasonNameText = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        createSeasonButton = new javax.swing.JButton();
        startBox = new javax.swing.JComboBox();
        endBox = new javax.swing.JComboBox();
        hotelsBox4 = new javax.swing.JComboBox();
        refreshButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        roomNumberText = new javax.swing.JTextField();
        roomTypeBox = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        bedTypeBox = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        createRoomButton = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        priceText = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        descriptionArea = new javax.swing.JTextArea();
        hotelsBox = new javax.swing.JComboBox();
        refreshButton = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        attractNameText = new javax.swing.JTextField();
        attractIDText = new javax.swing.JTextField();
        createAttractButton = new javax.swing.JButton();
        hotelsBox2 = new javax.swing.JComboBox();
        refreshButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        serviceNameText = new javax.swing.JTextField();
        serviceCodeText = new javax.swing.JTextField();
        createServiceButton = new javax.swing.JButton();
        hotelsBox3 = new javax.swing.JComboBox();
        refreshButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        exitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel8.setText("Code");

        jLabel9.setText("Name");

        jLabel10.setText("Start Date");

        jLabel11.setText("End Date");

        createSeasonButton.setText("Create Season");
        createSeasonButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createSeasonButtonActionPerformed(evt);
            }
        });

        startBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));

        endBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));

        refreshButton4.setText("Refresh");
        refreshButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(hotelsBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(refreshButton4))
                    .addComponent(createSeasonButton)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(seasonNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(startBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(seasonCodeText, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(endBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addContainerGap(484, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(seasonNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(seasonCodeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(startBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(endBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hotelsBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(refreshButton4))
                .addGap(18, 18, 18)
                .addComponent(createSeasonButton)
                .addGap(28, 28, 28))
        );

        jTabbedPane2.addTab("Seasons", jPanel3);

        jLabel1.setText("Room Number");

        jLabel2.setText("Room Type");

        roomNumberText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                roomNumberTextKeyTyped(evt);
            }
        });

        roomTypeBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Individual", "Double", "Family", "Suite" }));

        jLabel3.setText("Bed Type");

        bedTypeBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Individual", "Big Bed" }));

        jLabel5.setText("Room Description");

        createRoomButton.setText("Create Room");
        createRoomButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createRoomButtonActionPerformed(evt);
            }
        });

        jLabel13.setText("Price");

        descriptionArea.setColumns(20);
        descriptionArea.setRows(5);
        jScrollPane1.setViewportView(descriptionArea);

        refreshButton.setText("Refresh");
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jLabel5))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel13))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(roomTypeBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(roomNumberText))
                                    .addComponent(bedTypeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(priceText, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(79, 79, 79)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(createRoomButton)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(hotelsBox, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(39, 39, 39)
                                        .addComponent(refreshButton)))))))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(roomNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(roomTypeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(bedTypeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(priceText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hotelsBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(refreshButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(createRoomButton))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Rooms", jPanel2);

        jLabel23.setText("Name");

        jLabel24.setText("ID");

        createAttractButton.setText("Create Attractions");
        createAttractButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAttractButtonActionPerformed(evt);
            }
        });

        refreshButton2.setText("Refresh");
        refreshButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(createAttractButton)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(attractNameText, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                            .addComponent(attractIDText)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(hotelsBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(refreshButton2)))
                .addContainerGap(480, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(attractNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(attractIDText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hotelsBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(refreshButton2))
                .addGap(27, 27, 27)
                .addComponent(createAttractButton)
                .addGap(48, 48, 48))
        );

        jTabbedPane2.addTab("Attractions", jPanel5);

        jLabel21.setText("Name");

        jLabel22.setText("Code");

        createServiceButton.setText("Create Service");
        createServiceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createServiceButtonActionPerformed(evt);
            }
        });

        refreshButton3.setText("Refresh");
        refreshButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(createServiceButton)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel22)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(serviceCodeText))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel21)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(serviceNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(hotelsBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(refreshButton3)))
                .addContainerGap(488, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(serviceNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(serviceCodeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hotelsBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(refreshButton3))
                .addGap(31, 31, 31)
                .addComponent(createServiceButton)
                .addGap(43, 43, 43))
        );

        jTabbedPane2.addTab("Services", jPanel4);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 775, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 318, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Search", jPanel1);

        exitButton.setText("EXIT");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(329, 329, 329)
                .addComponent(exitButton)
                .addContainerGap(391, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(exitButton)
                .addContainerGap(146, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("EXIT", jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createRoomButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createRoomButtonActionPerformed
        
        String roomType = (String) roomTypeBox.getSelectedItem();
        String bedType = (String) bedTypeBox.getSelectedItem();
        
        //new price
        Price price = new Price();
        
        String description = descriptionArea.getText();
        String hotel = (String) hotelsBox.getSelectedItem();
        
        if(!roomNumberText.getText().equals("") && !priceText.getText().equals("") && !description.equals("")){
            
            int roomNumber = Integer.parseInt(roomNumberText.getText());
            price.setAmount(Integer.parseInt(priceText.getText()));
            
            if(Additional.findHotel(hotel) != null){
                if( Additional.findRoom(Additional.findHotel(hotel),roomNumber) == null){
                    if(roomNumber <= Additional.findHotel(hotel).getRoomsIn()){
                        if(roomType.equals("Individual")){
                            Additional.createRoom(hotel,roomNumber, roomType, bedType, 2, "Small", description, true, price);
                            roomNumberText.setText("");
                            priceText.setText("");
                            descriptionArea.setText("");
                        }
                        else if(roomType.equals("Double")){
                            
                            Additional.createRoom(hotel,roomNumber, roomType, bedType, 6, "Medium", description, true, price);
                            roomNumberText.setText("");
                            priceText.setText("");
                            descriptionArea.setText("");
                        }
                        else if(roomType.equals("Family")){
                            
                            Additional.createRoom(hotel,roomNumber, roomType, bedType, 8, "Big", description, true, price);
                            roomNumberText.setText("");
                            priceText.setText("");
                            descriptionArea.setText("");
                        }
                        else if(roomType.equals("Suite")){
                            
                            Additional.createRoom(hotel,roomNumber, roomType, bedType, 2, "Big", description, true, price);
                            roomNumberText.setText("");
                            priceText.setText("");
                            descriptionArea.setText("");
                        }
                    }
                    else{
                        JOptionPane.showMessageDialog(this, "Room number is out of range");
                        roomNumberText.setText("");
                        priceText.setText("");
                        descriptionArea.setText("");
                       
                    }
                }
                else{
                    JOptionPane.showMessageDialog(this, "Room number already used");
                    roomNumberText.setText("");
                }
            }
            else{
                JOptionPane.showMessageDialog(this, "Hotel doesn't exist");
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "It's necessary to fill every blank");
        }
    }//GEN-LAST:event_createRoomButtonActionPerformed

    private void roomNumberTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_roomNumberTextKeyTyped
        
        char confirm = evt.getKeyChar();
        
        if (Character.isLetter(confirm)){
            //asks if it is a letter
            getToolkit().beep();
            //makes a sound
            evt.consume();
            //avoids a digit
        } 
    }//GEN-LAST:event_roomNumberTextKeyTyped

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        if(hotelsBox.getSelectedIndex() == -1){
            for(int i=0; i < Additional.hotelList.size();i++){
                hotelsBox.addItem(Additional.hotelList.get(i).getName());
           
            }            
        }
        else{
            hotelsBox.removeAllItems();
            for(int i=0; i < Additional.hotelList.size();i++){
                hotelsBox.addItem(Additional.hotelList.get(i).getName());
           
            }   
        }

    }//GEN-LAST:event_refreshButtonActionPerformed

    private void refreshButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButton2ActionPerformed
        if(hotelsBox2.getSelectedIndex() == -1){
            for(int i=0; i < Additional.hotelList.size();i++){
                hotelsBox2.addItem(Additional.hotelList.get(i).getName());
           
            }            
        }
        else{
            hotelsBox2.removeAllItems();
            for(int i=0; i < Additional.hotelList.size();i++){
                hotelsBox2.addItem(Additional.hotelList.get(i).getName());
           
            }   
        }
    }//GEN-LAST:event_refreshButton2ActionPerformed

    private void refreshButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButton3ActionPerformed
        if(hotelsBox3.getSelectedIndex() == -1){
            for(int i=0; i < Additional.hotelList.size();i++){
                hotelsBox3.addItem(Additional.hotelList.get(i).getName());
           
            }            
        }
        else{
            hotelsBox3.removeAllItems();
            for(int i=0; i < Additional.hotelList.size();i++){
                hotelsBox3.addItem(Additional.hotelList.get(i).getName());
           
            }   
        }
    }//GEN-LAST:event_refreshButton3ActionPerformed

    private void createSeasonButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createSeasonButtonActionPerformed
        String name = seasonNameText.getText();
        String code = seasonCodeText.getText();
        String start = (String) startBox.getSelectedItem();
        String end = (String) endBox.getSelectedItem();
        String hotel = (String) hotelsBox4.getSelectedItem();        
        
        if(!name.equals("") && !code.equals("")){
            if(Additional.findHotel(hotel) != null){
                if(Additional.findSeason(Additional.findHotel(hotel), name) == null){
                    Additional.createSeason(hotel, name, code, start, end);
                    seasonNameText.setText("");
                    seasonCodeText.setText("");
                    
                }
                else{
                    JOptionPane.showMessageDialog(this, "Season already exist, dude");
                    seasonNameText.setText("");
                    seasonCodeText.setText("");
                }
            }
            else{
                 JOptionPane.showMessageDialog(this, "Hotel doesn't exist");
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "It's necessary to fill every blank");
        }
        
    }//GEN-LAST:event_createSeasonButtonActionPerformed

    private void createAttractButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAttractButtonActionPerformed
        String name = attractNameText.getText();
        String ID = attractIDText.getText();
        String hotel = (String) hotelsBox4.getSelectedItem();
        
        if(!name.equals("") && !ID.equals("")){
            if(Additional.findHotel(hotel) != null){
                if(Additional.findAttraction(Additional.findHotel(hotel), name) == null){
                    Additional.createAttraction(hotel, name, ID);
                    attractIDText.setText("");
                    attractNameText.setText("");
                    
                }
                else{
                    JOptionPane.showMessageDialog(this, "Attraction already exist, dude");
                    attractIDText.setText("");
                    attractNameText.setText("");
                }
            }
            else{
                JOptionPane.showMessageDialog(this, "Hotel doesn't exist");
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "It's necessary to fill every blank");
        }
    }//GEN-LAST:event_createAttractButtonActionPerformed

    private void createServiceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createServiceButtonActionPerformed
        String name = serviceNameText.getText();
        String code = serviceCodeText.getText();
        String hotel = (String) hotelsBox4.getSelectedItem();
        
        if(!name.equals("") && !code.equals("")){
            if(Additional.findHotel(hotel) != null){
                if(Additional.findService(Additional.findHotel(hotel), name) == null){
                    Additional.createService(hotel, name, code);
                    serviceNameText.setText("");
                    serviceCodeText.setText("");
                    
                }
                else{
                    JOptionPane.showMessageDialog(this, "Service already exist, dude");
                    serviceNameText.setText("");
                    serviceCodeText.setText("");
                }
            }
            else{
                JOptionPane.showMessageDialog(this, "Hotel doesn't exist");
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "It's necessary to fill every blank");
        }
    }//GEN-LAST:event_createServiceButtonActionPerformed

    private void refreshButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButton4ActionPerformed
        if(hotelsBox4.getSelectedIndex() == -1){
            for(int i=0; i < Additional.hotelList.size();i++){
                hotelsBox4.addItem(Additional.hotelList.get(i).getName());
           
            }            
        }
        else{
            hotelsBox4.removeAllItems();
            for(int i=0; i < Additional.hotelList.size();i++){
                hotelsBox4.addItem(Additional.hotelList.get(i).getName());
       
            }   
        }
    }//GEN-LAST:event_refreshButton4ActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_exitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdministratorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdministratorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdministratorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdministratorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdministratorView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField attractIDText;
    private javax.swing.JTextField attractNameText;
    private javax.swing.JComboBox bedTypeBox;
    private javax.swing.JButton createAttractButton;
    private javax.swing.JButton createRoomButton;
    private javax.swing.JButton createSeasonButton;
    private javax.swing.JButton createServiceButton;
    private javax.swing.JTextArea descriptionArea;
    private javax.swing.JComboBox endBox;
    private javax.swing.JButton exitButton;
    private javax.swing.JComboBox hotelsBox;
    private javax.swing.JComboBox hotelsBox2;
    private javax.swing.JComboBox hotelsBox3;
    private javax.swing.JComboBox hotelsBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField priceText;
    private javax.swing.JButton refreshButton;
    private javax.swing.JButton refreshButton2;
    private javax.swing.JButton refreshButton3;
    private javax.swing.JButton refreshButton4;
    public static javax.swing.JTextField roomNumberText;
    public static javax.swing.JComboBox roomTypeBox;
    private javax.swing.JTextField seasonCodeText;
    private javax.swing.JTextField seasonNameText;
    private javax.swing.JTextField serviceCodeText;
    private javax.swing.JTextField serviceNameText;
    private javax.swing.JComboBox startBox;
    // End of variables declaration//GEN-END:variables
}
